name: kernel_driver-dev
channels:
    - conda-forge
dependencies:
    - pip
    - pyzmq
    - python-dateutil
    - rich
    - xeus-python
    - ipykernel
    - pytest
    - pytest-asyncio
    - mypy
    - flake8
    - black
